[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-api"
version = "0.0.0"
description = "Foundation model access library"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2",
    "pydantic-settings>=2",
    "tiktoken>=0.5.1",
    "openai>=1.0",
    "boto3>=1.34",
    "pandas>=2.1"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "-ra"
