"""
Centralized log-noise controls for Presidio integration.

This module suppresses known repetitive Presidio warnings that do not impact
runtime behavior for this library's supported language configuration.
"""

from __future__ import annotations

import logging

PRESIDIO_ANALYZER_LOGGER_NAME: str = "presidio-analyzer"
PRESIDIO_LANGUAGE_MISMATCH_WARNING_SUBSTRING: str = (
    "Recognizer not added to registry because language is not supported by registry"
)
PRESIDIO_ENTITY_RECOGNIZER_WARNING_SUBSTRING: str = (
    "doesn't have the corresponding recognizer in language"
)
PRESIDIO_LOADED_RECOGNIZER_INFO_SUBSTRING: str = "Loaded recognizer:"
PRESIDIO_USING_DEVICE_INFO_SUBSTRING: str = "Using device of type:"
PRESIDIO_CREATED_NLP_ENGINE_INFO_SUBSTRING: str = "Created NLP engine:"
PRESIDIO_DEFAULT_REGISTRY_INFO_SUBSTRING: str = (
    "registry not provided, creating default."
)
PRESIDIO_SKIP_CONTEXT_EXTRACTION_INFO_SUBSTRING: str = (
    "Skipping context extraction due to lack of NLP artifacts"
)


class PresidioKnownWarningNoiseFilter(logging.Filter):
    """
    Filters known noisy Presidio warning records that are not actionable.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        """
        Determines whether a given log record should be emitted.

        Args:
            record: Logging record candidate generated by the Presidio stack.

        Returns:
            False when the log matches the known non-actionable Presidio warning
            pattern, otherwise True.
        """
        str_message: str = record.getMessage()
        bool_is_known_language_mismatch_warning: bool = (
            record.name == PRESIDIO_ANALYZER_LOGGER_NAME
            and PRESIDIO_LANGUAGE_MISMATCH_WARNING_SUBSTRING in str_message
        )
        bool_is_known_missing_entity_recognizer_warning: bool = (
            record.name == PRESIDIO_ANALYZER_LOGGER_NAME
            and record.levelno == logging.WARNING
            and PRESIDIO_ENTITY_RECOGNIZER_WARNING_SUBSTRING in str_message
        )
        bool_is_known_loaded_recognizer_info: bool = (
            record.name == PRESIDIO_ANALYZER_LOGGER_NAME
            and record.levelno == logging.INFO
            and PRESIDIO_LOADED_RECOGNIZER_INFO_SUBSTRING in str_message
        )
        bool_is_known_using_device_info: bool = (
            record.name == PRESIDIO_ANALYZER_LOGGER_NAME
            and record.levelno == logging.INFO
            and PRESIDIO_USING_DEVICE_INFO_SUBSTRING in str_message
        )
        bool_is_known_created_nlp_engine_info: bool = (
            record.name == PRESIDIO_ANALYZER_LOGGER_NAME
            and record.levelno == logging.INFO
            and PRESIDIO_CREATED_NLP_ENGINE_INFO_SUBSTRING in str_message
        )
        bool_is_known_default_registry_info: bool = (
            record.name == PRESIDIO_ANALYZER_LOGGER_NAME
            and record.levelno == logging.INFO
            and PRESIDIO_DEFAULT_REGISTRY_INFO_SUBSTRING in str_message
        )
        bool_is_known_skip_context_extraction_info: bool = (
            record.name == PRESIDIO_ANALYZER_LOGGER_NAME
            and record.levelno == logging.INFO
            and PRESIDIO_SKIP_CONTEXT_EXTRACTION_INFO_SUBSTRING in str_message
        )
        if bool_is_known_language_mismatch_warning:
            # Early return because this warning is known noise for supported setups.
            return False
        if bool_is_known_loaded_recognizer_info:
            # Early return because recognizer-load chatter is non-actionable noise.
            return False
        if bool_is_known_using_device_info:
            # Early return because model-device selection chatter is non-actionable noise.
            return False
        if bool_is_known_created_nlp_engine_info:
            # Early return because NLP engine creation chatter is non-actionable noise.
            return False
        if bool_is_known_default_registry_info:
            # Early return because default registry creation chatter is non-actionable noise.
            return False
        if bool_is_known_skip_context_extraction_info:
            # Early return because regex-profile context-skip chatter is non-actionable noise.
            return False
        if bool_is_known_missing_entity_recognizer_warning:
            # Early return because this warning is expected for regex-only profiles.
            return False
        # Normal return for all other log records.
        return True


_BOOL_PRESIDIO_NOISE_FILTER_INSTALLED: bool = False


def configure_presidio_log_noise_filter() -> None:
    """
    Installs the Presidio noise filter exactly once per process.

    Args:
        None

    Returns:
        None after ensuring the Presidio warning-noise filter is registered.
    """
    global _BOOL_PRESIDIO_NOISE_FILTER_INSTALLED

    if _BOOL_PRESIDIO_NOISE_FILTER_INSTALLED:
        # Early return because the Presidio warning filter was already installed.
        return None

    logger_presidio_analyzer: logging.Logger = logging.getLogger(
        PRESIDIO_ANALYZER_LOGGER_NAME
    )
    logger_presidio_analyzer.addFilter(PresidioKnownWarningNoiseFilter())
    _BOOL_PRESIDIO_NOISE_FILTER_INSTALLED = True
    # Normal return after one-time filter installation.
    return None
